
//v1.2 hide cluster and move ctrl to cluster position
//source "superToonFacialProcs.mel";

global proc kz_secondaryCtrl()
{

    $win = "kz_secCtrl";
    if (`window -exists $win`)
        deleteUI $win;

    window -title "Secondary Control v1.2" $win;
    columnLayout -adj true;

    $skinClusterTextGrp = `textFieldButtonGrp -l "SkinCluster Node:" -cw1 80 -enable 1 -bl "Load Sel" skinClusterTextGrp`;
    $baseObjectTextGrp = `textFieldButtonGrp -l "Base Object:" -cw1 80 -enable 1 -bl "Load Sel" baseObjectTextGrp`;
    $button = `button   -l "Go" -h 60 -c ("createSecondControlCmd()" )`;
    $button2 = `button   -l "Pin to Mesh" -h 40 -c ("pinToMeshCmd()" )`;
    $logo=`text -label "TimeLine Stuido"  -align "right"`;
    
    textFieldButtonGrp -e
        -bc ("loadSelectedIntoButtonGrp \"" + $skinClusterTextGrp + "\"")
        //-cc ("js_addAllAttrsToAttrTSL \""+$skinClusterTextGrp+"\" \""+ $skinClusterTextGrp + "\"")
        $skinClusterTextGrp;
    textFieldButtonGrp -e
        -bc ("loadSelectedIntoButtonGrp \"" + $baseObjectTextGrp + "\"") $baseObjectTextGrp;
    showWindow $win;
    
}
global proc loadSelectedIntoButtonGrp (string $buttonGrp)
{
    string $objs[0];
    $objs = `ls -sl`;
    if (size($objs) > 0)
    {
        textFieldButtonGrp -e -tx $objs[0] $buttonGrp;
    }
}
global proc createSecondControlCmd ()
{
    string $skinCluster=`textFieldButtonGrp -q -tx skinClusterTextGrp`;
    string $base=`textFieldButtonGrp -q -tx baseObjectTextGrp`;
    skinClusterToCluster $skinCluster $base cluster;
    select -cl;
    print "successfully Created Sec. Controls";
}
global proc pinToMeshCmd ()
{
    string $objs[] = `ls -sl`;
    hyperRealMeshParent;
    select -cl;
    select -r $objs;
    select -d $objs[0];
    string $secCtrls[] = `ls -sl`;
    controlCircleCreator $secCtrls 1 0 0 .25;
    select -cl;
}
global proc controlCircleCreator (string $sel[], float $x, float $y, float $z, float $r)
{
    string $joint;
    for ($joint in $sel)
    {
        string $shapes[] = `listRelatives -s $joint`;
        if (`size $shapes`) hide $shapes[0];
        else setAttr ($joint+".drawStyle") 2;
        
        //float $loc[] = `xform -q -ws -t $joint`;
        float $loc[] = `xform -q -sp $joint`;
        //circle -fp $loc[0] $loc[1] $loc[2] -sw 360 -nr $x $y $z  -r $r -n ($joint + "_control");
        curve -d 1 -p -0.5 0.5 0.5 -p 0.5 0.5 0.5 -p 0.5 0.5 -0.5 
        -p -0.5 0.5 -0.5 -p -0.5 0.5 0.5 -p -0.5 -0.5 0.5 -p 0.5 -0.5 
        0.5 -p 0.5 -0.5 -0.5 -p -0.5 -0.5 -0.5 -p -0.5 -0.5 0.5 -p -0.5 
        0.5 0.5 -p -0.5 0.5 -0.5 -p -0.5 -0.5 -0.5 -p 0.5 -0.5 -0.5 
        -p 0.5 0.5 -0.5 -p 0.5 0.5 0.5 -p 0.5 -0.5 0.5 -k 0 -k 1 -k 2 
        -k 3 -k 4 -k 5 -k 6 -k 7 -k 8 -k 9 -k 10 -k 11 -k 12 -k 13 -k 14 -k 15 -k 16 ;
        rename ($joint + "_control");
        move -r $loc[0] $loc[1] $loc[2] ($joint + "_control");
        makeIdentity -apply true -t 1 -r 1 -s 1 -n 0 -pn 1 ($joint + "_control");        
        
        parent -r -shape ($joint + "_controlShape") $joint;
        setAttr ($joint + "_controlShape.overrideEnabled") 1;
        setAttr ($joint + ".overrideEnabled") 1;
        //setAttr ($joint + ".radius") 0;
        if(`gmatch $joint "*C_*"`){
            // if center color override is yellow
            setAttr ($joint + "_controlShape.overrideColor") 17;
            setAttr ($joint + ".overrideColor") 17;
            }
        else if(`gmatch $joint "*L_*"`){
            // if left color override is green
            setAttr ($joint + "_controlShape.overrideColor") 6;
            setAttr ($joint + ".overrideColor") 6;
            }
        else if(`gmatch $joint "*R_*"`){
            // if right color override is red
            setAttr ($joint + "_controlShape.overrideColor") 13;
            setAttr ($joint + ".overrideColor") 13;
            }
        else if(`gmatch $joint "*"`){
            // if cant match, make blue
            setAttr ($joint + "_controlShape.overrideColor") 6;
            setAttr ($joint + ".overrideColor") 6;
            }   
        delete ($joint + "_control");               
        }
}