global string $gShelfTopLevel;
string $currentShelf = `tabLayout -query -selectTab $gShelfTopLevel`;
setParent $currentShelf;
string $asInstallScriptLocation=`asInstallScriptLocation`;
if (`gmatch $asInstallScriptLocation "*\*"`)
	$asInstallScriptLocation=`substituteAllString $asInstallScriptLocation "\\" "/"`;
string $scriptName="Maya_SpringSolving";
string $command="import sys \nimport os\n"+"sys.path.append(\""+$asInstallScriptLocation+"\")\n" +"ver=int(\"%s%s\" % (sys.version_info[0], sys.version_info[1]))\n"+"if ver==27:\n"+"    from Maya_SpringSolving_py27 import SpringSolving;a=SpringSolving()\n"+"elif ver==37:\n"+"    from Maya_SpringSolving_py37 import SpringSolving;a=SpringSolving()\n"+"elif ver==39:\n"+"    from Maya_SpringSolving_py39 import SpringSolving;a=SpringSolving()\n"+"elif ver==311:\n"+"    from Maya_SpringSolving_py311 import SpringSolving;a=SpringSolving()\n"+"else:\n"+"    cmds.confirmDialog(message='Not supported by the current Python version')";
string $icon="curveEP.png";
shelfButton
	-command $command
	-annotation $scriptName
	-label $scriptName
	-image  $icon
	-image1 $icon
	-sourceType "python"
;
global proc asInstallScriptLocator (){}

global proc string asInstallScriptLocation ()
{
string $whatIs=`whatIs asInstallScriptLocator`;
string $fullPath=`substring $whatIs 25 999`;
string $buffer[];
string $slash="/";
if (`gmatch $whatIs "*\\\\*"`)//sourced from ScriptEditor
	$slash="\\";
int $numTok=`tokenize $fullPath $slash $buffer`;
int $numLetters=size($fullPath);
int $numLettersLastFolder=size($buffer[$numTok-1]);
string $scriptLocation=`substring $fullPath 1 ($numLetters-$numLettersLastFolder)`;
return $scriptLocation;
}