# -*- coding: utf-8 -*-
"""
Animatrix Polisher launcher (__init__.py)

- Ensures package, scripts, and pyarmor_runtime_* are importable
- Imports the obfuscated main file by absolute path (no bare module import)
- Tries multiple entrypoints: start(), launch(), run(), main(), or class AnimatrixPolisherCmds
- Works with Maya 2023–2026 (Py 3.9/3.10/3.11) as long as the package was obfuscated with matching mayapy
"""

from __future__ import annotations
import os, sys, glob, importlib.util, importlib, traceback

# ---------------------------------------------------------------------------
# 1) Make sure we can import pyarmor runtime and the package itself (like Sonic)
# ---------------------------------------------------------------------------
_pkg_dir     = os.path.dirname(__file__)                 # .../scripts/AnimatrixPolisher
_scripts_dir = os.path.dirname(_pkg_dir)                 # .../scripts

for p in (_pkg_dir, _scripts_dir):
    if p and p not in sys.path:
        sys.path.insert(0, p)

# Add any pyarmor_runtime_* folder found under package AND scripts root
for base in (_pkg_dir, _scripts_dir):
    try:
        for rt in glob.glob(os.path.join(base, 'pyarmor_runtime_*')):
            if os.path.isdir(rt) and rt not in sys.path:
                sys.path.insert(0, rt)
    except Exception:
        pass

# ---------------------------------------------------------------------------
# 2) Locate the main obfuscated file (generated by PyArmor)
#    Default we expect: AnimatrixPolisher/animatrix_polisher.py
#    But we search a few candidates just in case.
# ---------------------------------------------------------------------------
_CANDIDATE_FILES = [
    'animatrix_polisher.py',       # preferred (your source name)
    'AnimatrixPolisher.py',        # fallback (different casing)
    # obfuscated single-file names you might use:
    'animatrix.py',
    '_animatrix.py',
]

def _find_main_file() -> str | None:
    for name in _CANDIDATE_FILES:
        fp = os.path.join(_pkg_dir, name)
        if os.path.isfile(fp):
            return fp
    # Last resort: pick any *.py that contains 'pyarmor_runtime' import
    try:
        for fp in glob.glob(os.path.join(_pkg_dir, '*.py')):
            try:
                with open(fp, 'r', encoding='utf-8', errors='ignore') as f:
                    txt = f.read(2048)
                if 'pyarmor_runtime_' in txt:
                    return fp
            except Exception:
                continue
    except Exception:
        pass
    return None

# ---------------------------------------------------------------------------
# 3) Import-by-path helper (avoid package name mismatches)
# ---------------------------------------------------------------------------
def _import_by_path(py_file: str):
    """
    Import a module from an absolute file path with a unique module name.
    """
    mod_name = 'AnimatrixPolisher.__main__'
    spec = importlib.util.spec_from_file_location(mod_name, py_file)
    if spec is None or spec.loader is None:
        raise ImportError("Failed to create import spec for: %s" % py_file)
    mod = importlib.util.module_from_spec(spec)
    # Allow relative imports inside obfuscated file (if any)
    sys.modules[mod_name] = mod
    spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    return mod

# ---------------------------------------------------------------------------
# 4) Public launcher
# ---------------------------------------------------------------------------
def launch(reload_module: bool = False):
    """
    Launch Animatrix Polisher UI.

    Parameters
    ----------
    reload_module : bool
        If True, remove previously loaded module before re-importing by path.
    """
    main_file = _find_main_file()
    if not main_file:
        _warn("Animatrix Polisher launch failed: main .py not found in package.")
        return

    # Optional aggressive cleanup (usually not needed, but keeps re-runs tidy)
    if reload_module:
        for key in list(sys.modules.keys()):
            if key.startswith('AnimatrixPolisher.__main__'):
                sys.modules.pop(key, None)

    try:
        mod = _import_by_path(main_file)
    except ModuleNotFoundError as e:
        # Helpful hint for missing pyarmor runtime
        if 'pyarmor_runtime_' in str(e):
            _warn("Animatrix Polisher launch failed: %s\n"
                  "Tip: ensure 'pyarmor_runtime_*' is copied alongside the package (like Sonic) "
                  "and that this __init__.py adds it to sys.path." % e)
        else:
            _warn("Animatrix Polisher launch failed: %s" % e)
        _print_tb()
        return
    except Exception as e:
        _warn("Animatrix Polisher import error: %s" % e)
        _print_tb()
        return

    # Try common entrypoints in order
    for entry in ('start', 'launch', 'run', 'main'):
        fn = getattr(mod, entry, None)
        if callable(fn):
            try:
                fn()
                return
            except Exception as e:
                _warn("Animatrix Polisher entrypoint '%s' failed: %s" % (entry, e))
                _print_tb()
                # try next entry

    # Fallback: try instantiating main UI class if present
    for cls_name in ('AnimatrixPolisherCmds', 'AnimatrixPolisherUI'):
        cls = getattr(mod, cls_name, None)
        if cls:
            try:
                ui = cls()  # noqa: F841 (keep reference alive in module scope)
                return
            except Exception as e:
                _warn("Animatrix Polisher class '%s' failed: %s" % (cls_name, e))
                _print_tb()
                # try next class

    _warn("Animatrix Polisher launched module but no entrypoint was usable.\n"
          "Ensure your main file defines start()/launch() or class AnimatrixPolisherCmds.")

# Short alias
def start():
    launch()

# ---------------------------------------------------------------------------
# 5) Small helpers
# ---------------------------------------------------------------------------
def _warn(msg: str):
    try:
        import maya.cmds as cmds
        cmds.warning(msg)
    except Exception:
        print("[AnimatrixPolisher] WARNING:", msg)

def _print_tb():
    try:
        traceback.print_exc()
    except Exception:
        pass

__all__ = ['launch', 'start']
